### ISSUE TITLE
[Bug]: sendmail: Cannot open mailhub:25

### ISSUE THREAD

**Issue by hanscees** [manios/docker-nagios#67]
### What happened?

Hi,

My nagios is at last working but it wont send email with this error:  stderr line 01: sendmail: Cannot open mailhub:25
It probably has to do with the fact that I used another account for the main user nagiosadmin. 

I found this tip somewhere: https://unix.stackexchange.com/questions/351401/ssmtp-not-sending-mails-cannot-open-mailhub25-tldr-file-permissions-when-u

and tried this: chmod 777 /etc/ssmtp /etc/ssmtp/*

but that does not work. 

where is the ssmtp configuration? Or how do you fill your mailhub variable? 

### Image information

* maintainer: Christos Manios <maniopaido@gmail.com>
* nagiosPluginsVersion: 2.4.7
* nagiosVersion: 4.5.0
* name: Nagios
* nrpeVersion: 4.1.0
* org.opencontainers.image.authors: Christos Manios <maniopaido@gmail.com>
* org.opencontainers.image.description: Nagios, the Industry Standard In IT Infrastructure Monitoring
* org.opencontainers.image.documentation: https://github.com/manios/docker-nagios/blob/master/README.md
* org.opencontainers.image.licenses: MIT
* org.opencontainers.image.revision: 6b550aa657ddd16c8d6283cd15dfd4d495115f46
* org.opencontainers.image.source: https://github.com/manios/docker-nagios

### Image architecture

x86

### Relevant log output

I logged into the container 

root@deb-2024-template:~/containers/nagios# docker exec -it nagios-nagios-1 bash
bash-5.0# echo yo | /usr/sbin/sendmail -v hanscees@hanscees.com
sendmail: Cannot open mailhub:25
bash-5.0# whoami
root

**Comment by hanscees** [comment]
strangely enough /etc/ssmtp seems to be empty

bash-5.0# ls -all /etc/ssmtp
total 12
drwxrwxrwx    2 root     root          4096 Feb 24 20:01 .
drwxr-xr-x    1 root     root          4096 Feb 26 19:49 ..

**Comment by hanscees** [comment]
after creating /etc/ssmtp/ssmtp.conf 

and filling it, it works. 

darn, thats nice.

**Comment by manios** [comment]
Hi @hanscees !

Sorry for the late response! If you mount a volume to `/etc/ssmtp/` then this container checks if the directory is empty and if it does, it adds a sample `ssmtp.conf` file. You can find it here: [overlay/etc/ssmtp/ssmtp.conf](https://github.com/manios/docker-nagios/blob/master/overlay/etc/ssmtp/ssmtp.conf).

Since it was not that clear, I have updated the `README.md` file accordingly in 2bdffc955a3c0dcd51c87e38d4fa72ad1b914564.

If I understand correctly you fixed it yourself, right? If so , you may close the issue. Thanks!
